name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: create release
        run: gh release create "v${{ github.ref_name }}" -t "v${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: [release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: cargo build --release -j`nproc`
      - run: |
          mv target/release/nomino nomino-linux-64bit
          gh release upload "v${{ github.ref_name }}" nomino-linux-64bit --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    needs: [release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: cargo build --release -j`sysctl -n hw.physicalcpu`
      - run: |
          mv target/release/nomino nomino-macos-64bit
          gh release upload "v${{ github.ref_name }}" nomino-macos-64bit --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    needs: [release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: cargo build --release
      - run: |
          mv target/release/nomino.exe nomino-windows-64bit.exe
          gh release upload "v${{ github.ref_name }}" nomino-windows-64bit.exe --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
